language: scala
scala:
  - 2.11.8
  
env:
  global:
    - secure: "ZdZ6oYuUT9JwCNcYoAa8rIFIwVoMlemBfMcf8faZw9m71gJlDR0lN01NvaYfvXCCUtIr5uFdGCpntQ2ZsJLze8RsqLz8SzDPC492TZQYMlv2AyXXRnwEyAMTzVzK96bRUnCaQPTGbt/w+PXZpfLOpqPCErzAN/nJIPUBY+T8pcBRbgesTIwmVkreVsj0c5cKAcsELFHGZC1NJLH9N4NHisG5j+gf0RaIA+RCjMqkOLfBh8lzwqmMhQQlJVpN6+Bo4PB3M9dDemNFvm2WjsG16jm/2no/HwRdvAP4Ygwu86d4ZjC++rFEFARBvUqJu6KqVolYWRHByHYPdba9uI4uJEBRhoaVX5zPry2AO6edJf01+BDSDo1QoLMXVWvQoCBs1Bsz8+6Ew7nEML2oFnd7JacXTFSK8mwobTsoYwgyGsIAxWgfAgSF1u6hlxu3I41V87E9kBm+clucfzyACk1v+2bDKrCi0M6e2b5Z3kPsYF2hjGJgzKK6HGTtI0Bx0Kx2p7X2wZEGRlV2YKtda5qg/m9iW/LYBYkZbuPry3XesLQYG4C2cW7mrB9Rrftrvm9SVlx/OPKtLgjBTFp8XYvIahpMx9S4UKoG7h/taP5Vik9f/XMwYvCL9b295yWt+cqcUwKgYMWjVDdElVGM4OqJgO7WM5JCcZp/+bwA3sSMTGw="
    - TIMEOUT=1000